name: Docker

on:
  workflow_call:
jobs:
  docker:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: ['ubuntu-latest'] 
    steps:
    - uses: actions/checkout@v3
    - name: Docker setup build
      uses: docker/setup-buildx-action@v3.7.1
      
