name: Entrega Contínua 

on:
    workflow_call:

jobs:
 
  EC2:
    runs-on: ubuntu-latest
    steps:

     - name: Download a Build Artifact
       uses: actions/download-artifact@v4.1.8
       with:
    # Name of the artifact to download. If unspecified, all artifacts for the run are downloaded.
        name: go_compiled
     - uses: actions/checkout@v3 # arquivos estaticos da aplicação que nao vai no binario compilado

     - name: Deploy to Staging server
       uses: easingthemes/ssh-deploy@main
       with:
           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
           REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
           REMOTE_USER: ${{ secrets.REMOTE_USER }}
           TARGET: ${{ secrets.REMOTE_TARGET }}
           EXCLUDE: "/dist/, /node_modules/"
        
